{% set name = "opentelemetry-instrumentation-falcon" %}
{% set version = "0.24b0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry-instrumentation-falcon-{{ version }}.tar.gz
  sha256: 04fc144ac891433a86197233f580766ca59660df9c7c711de4897b9f771d0482

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.4
  run:
    - opentelemetry-api ~=1.3
    - opentelemetry-instrumentation ==0.24b0
    - opentelemetry-instrumentation-wsgi ==0.24b0
    - opentelemetry-semantic-conventions ==0.24b0
    - opentelemetry-util-http ==0.24b0
    - python >=3.4
    # - parameterized ==0.7.4
    # - opentelemetry-test ==0.24b0
    # - falcon ~=2.0

test:
  imports:
    - opentelemetry
    - opentelemetry.instrumentation
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-falcon
  summary: Falcon instrumentation for OpenTelemetry
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
