{% set name = "opentelemetry-instrumentation-falcon" %}
{% set version = "0.26b1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry-instrumentation-falcon-{{ version }}.tar.gz
  sha256: 76e77e151ddb455f040f3ef21735935f48cdf45a34af7e95c5c3278754e95a5f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.4
  run:
    - opentelemetry-api ~=1.3
    - opentelemetry-instrumentation ==0.26b1
    - opentelemetry-instrumentation-wsgi ==0.26b1
    - opentelemetry-semantic-conventions ==0.26b1
    - opentelemetry-util-http ==0.26b1
    - python >=3.4
    # - parameterized ==0.7.4
    # - opentelemetry-test ==0.24b0
    # - falcon ~=2.0
    # - parameterized ==0.7.4
    # - opentelemetry-test-utils ==0.26b1
    # - falcon <4.0.0,>=2.0.0

test:
  imports:
    - opentelemetry
    - opentelemetry.instrumentation
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-falcon
  summary: Falcon instrumentation for OpenTelemetry
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
