{% set name = "opentelemetry-instrumentation-falcon" %}
{% set version = "0.30b1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry-instrumentation-falcon-{{ version }}.tar.gz
  sha256: 9e241338b293289af1d3e6018f1258d43049ba75bbe951e3e32b8d957c574b99

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.4
  run:
    - opentelemetry-api ~=1.3
    - opentelemetry-instrumentation ==0.30b1
    - opentelemetry-instrumentation-wsgi ==0.30b1
    - opentelemetry-semantic-conventions ==0.30b1
    - opentelemetry-util-http ==0.30b1
    - python >=3.4
    - parameterized ==0.7.4
    - packaging >=20.0
    # - opentelemetry-test-utils ==0.30b0
    - falcon <4.0.0,>=1.4.1
    # - opentelemetry-test-utils ==0.30b1

test:
  imports:
    - opentelemetry
    - opentelemetry.instrumentation
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-falcon
  summary: Falcon instrumentation for OpenTelemetry
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
